Create MANIFEST.in (#7)
* Create MANIFEST.in

Hello Daniel,

some files are missing in the SDIST on Pypi, so I added this file.
Otherwise, the SDIST can't be compiled:

```
>>> Jobs: 9 of 10 complete, 1 failed                Load avg: 0.93, 0.30, 0.10
 * Package:    dev-python/Adax-local-0.1.3
 * Repository: HomeAssistantRepository
 * Maintainer: b@edevau.net
 * Upstream:   mail@dahoiv.net
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python3_9 test userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking Adax-local-0.1.3.tar.gz to /var/tmp/portage/dev-python/Adax-local-0.1.3/work
>>> Source unpacked in /var/tmp/portage/dev-python/Adax-local-0.1.3/work
>>> Preparing source in /var/tmp/portage/dev-python/Adax-local-0.1.3/work/Adax-local-0.1.3 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/Adax-local-0.1.3/work/Adax-local-0.1.3 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/Adax-local-0.1.3/work/Adax-local-0.1.3 ...
 * python3_9: running distutils-r1_run_phase distutils-r1_python_compile
python3.9 setup.py build -j 6
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/Adax-local-0.1.3/work/Adax-local-0.1.3/setup.py", line 6, in <module>
    with pathlib.Path("requirements.txt").open() as requirements_txt:
  File "/usr/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
 * ERROR: dev-python/Adax-local-0.1.3::HomeAssistantRepository failed (compile phase):
 *   (no error message)
 *
 * Call stack:
 *     ebuild.sh, line  127:  Called src_compile
 *   environment, line 2930:  Called distutils-r1_src_compile
 *   environment, line 1255:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
 *   environment, line  490:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2608:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2149:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2147:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line  782:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
 *   environment, line 1246:  Called distutils-r1_python_compile
 *   environment, line 1029:  Called esetup.py 'build' '-j' '6'
 *   environment, line 1688:  Called die
 * The specific snippet of code:
 *       "${@}" || die -n;
```

Btw, I hope you don't mind I use your component in https://github.com/onkelbeh/HomeAssistantRepository, like I do already with many of your other work.

* Update MANIFEST.in

Co-authored-by: Daniel Hjelseth Høyer <mail@dahoiv.net>

Co-authored-by: Daniel Hjelseth Høyer <mail@dahoiv.net>